{{- if and (.Values.redcap.install.enabled) (empty .Values.redcap.install.overrideInstallContainer) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-config-script
data: 
{{ tpl (.Files.Glob "configuration/redcap/init/redcap-config.sh").AsConfig . | nindent 2 }}
{{- end }}
