apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-load-scenarios
data:
  test-1-200.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '30s', target: 50 },
        { duration: '1m', target: 200 },
        { duration: '1m', target: 200 },
        { duration: '1m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<3000'],
        http_req_failed: ['rate<0.01'],
      },
    };

    export default function () {
      http.get(`${__ENV.TARGET_URL}`);
      sleep(1);
    }

  test-2-500.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '10s', target: 100 },
        { duration: '1m', target: 500 },
        { duration: '1m', target: 500 },
        { duration: '1m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<3000'],
        http_req_failed: ['rate<0.01'],
      },
    };

    export default function () {
      http.get(`${__ENV.TARGET_URL}`);
      sleep(1);
    }

  test-3-2000.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '10s', target: 500 },
        { duration: '1m', target: 2000 },
        { duration: '1m', target: 2000 },
        { duration: '1m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<3000'],
        http_req_failed: ['rate<0.01'],
      },
    };

    export default function () {
      http.get(`${__ENV.TARGET_URL}`);
      sleep(1);
    }

  test-4-5000.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '10s', target: 1000 },
        { duration: '1m', target: 5000 },
        { duration: '1m', target: 5000 },
        { duration: '1m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<3000'],
        http_req_failed: ['rate<0.01'],
      },
    };

    export default function () {
      http.get(`${__ENV.TARGET_URL}`);
      sleep(1);
    }

  test-5-20000.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '10s', target: 5000 },
        { duration: '1m', target: 20000 },
        { duration: '1m', target: 20000 },
        { duration: '1m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<3000','p(95) < 800', 'p(99.9) < 2000'],
        http_req_failed: ['rate<0.01'],
      },
    };

    export default function () {
      http.get(`${__ENV.TARGET_URL}`);
      sleep(1);
    }

