apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '2m', target: 5000 },
        { duration: '3m', target: 20000 },
        { duration: '5m', target: 20000 },
        { duration: '2m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p95<3000'], // p95 ≤ 3 秒
        http_req_failed: ['rate<0.01'],  // 錯誤率 ≤ 1%
      },
    };

    const BASE_URL = __ENV.TARGET_URL; // 從 env 拿 URL

    export default function () {
      http.get(`${BASE_URL}/`);
      sleep(1);
    }

