apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-minimal-script
data:
  script.js: |
    import http from 'k6/http';
    import { check } from 'k6';

    export default function () {
      const res = http.get(__ENV.TARGET_URL);
      check(res, {
        'status is 200': (r) => r.status === 200
      });
    }

