apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  completions: 20
  parallelism: 20
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "/scripts/script.js", "--vus", "1000", "--duration", "10m"]
          envFrom:
            - configMapRef:
                name: k6-config   # 將 k6-config 內的所有 key 注入環境變數
          volumeMounts:
            - name: k6-script
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: k6-script
          configMap:
            name: k6-script

