apiVersion: batch/v1
kind: CronJob
metadata:
  name: redcap-backup-job
  labels:
    app.kubernetes.io/name: redcap-backup-job
    app.kubernetes.io/instance: redcap
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
          containers:
          - name: redcap-backup
            image: bitnamilegacy/mysql:9.3.0-debian-12-r1
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c", "chmod +x /scripts/backup.sh && /scripts/backup.sh"]
            envFrom:
            - configMapRef:
                name: redcap-db-config
            - secretRef:
                name: redcap-database-credentials
            volumeMounts:
            - name: redcap-code
              mountPath: /redcap
            - name: edocs
              mountPath: /edocs
            - name: backup-pvc
              mountPath: /backup-data
            - name: backup-scripts
              mountPath: /scripts
          volumes:
          - name: redcap-code
            persistentVolumeClaim:
              claimName: redcap-app-pvc
          - name: edocs
            persistentVolumeClaim:
              claimName: redcap-edocs-pvc
          - name: backup-pvc
            persistentVolumeClaim:
              claimName: redcap-backup-pvc
          - name: backup-scripts
            configMap:
              name: redcap-backup-scripts
              defaultMode: 0755

