{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-app-ingress
spec:
  podSelector:
    matchLabels:
      {{ include "redcap.networkPolicy.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      {{- if .Values.redcap.install.enabled }}
      - podSelector:
          matchLabels:
            {{ include "redcap.initJob.networkPolicy.selectorLabels" . | nindent 12 }}
      {{- end }}
      - podSelector:
          matchLabels:
            {{ include "redcap.adminJob.networkPolicy.selectorLabels" . | nindent 12 }}
      - podSelector:
          matchLabels:
            {{ include "httpd.networkPolicy.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.redcap.targetPort }}
{{- end }}