{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-app-egress
spec:
  podSelector:
    matchLabels:
      {{ include "redcap.networkPolicy.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # allow egress to REDCap external services (URL Shortener, etc. cd. Configuration Check details in Admin menu)
    - to:
      ports:
        - protocol: TCP
          port: 443

    # allow egress to mail server
    - to:
      ports:
        - protocol: TCP
          port: {{ .Values.redcap.config.mail.auth.port }}
    # allow egress to database
    - to:
      - podSelector:
          matchLabels:
            {{- range $labelKey, $labelValue := .Values.mysql.primary.podLabels }}
              {{ $labelKey | nindent 12 }}: {{ $labelValue }}
            {{- end }}
      ports:
        - protocol: TCP
          port: {{ default 3306 .Values.mysql.primary.service.ports.mysql }}
    
    # allow DNS resolution
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}