{{- if and (.Values.httpd.enabled) (.Values.networkPolicies.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-httpd-ingress
spec:
  podSelector:
    matchLabels:
      {{ include "httpd.networkPolicy.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      ports:
        - protocol: TCP
          port: {{ .Values.service.httpd.targetPort }}
{{- end }}