apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-auto-limit-test
data:
  auto-limit.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';
    import { Trend, Rate } from 'k6/metrics';

    // è‡ªè¨‚æŒ‡æ¨™
    let responseTime = new Trend('response_time');
    let errorRate = new Rate('error_rate');

    const BASE_URL = __ENV.TARGET_URL || 'https://example.com';
    const STEP_DURATION = __ENV.STEP_DURATION || '60s'; // æ¯å€‹éšŽæ®µé•·åº¦
    const MAX_VU = parseInt(__ENV.MAX_VU || '50000');   // æœ€å¤§è™›æ“¬ä½¿ç”¨è€…
    const STEP_SIZE = parseInt(__ENV.STEP_SIZE || '1000'); // æ¯æ¬¡å¢žåŠ çš„ä½¿ç”¨è€…æ•¸

    // åŸºæœ¬æ¸¬è©¦å‹•ä½œ
    export default function () {
      let res = http.get(`${BASE_URL}/`);
      responseTime.add(res.timings.duration);
      errorRate.add(res.status >= 400);
      sleep(1);
    }

    // è‡ªå‹•åŒ–éšŽæ®µç”Ÿæˆ
    export let options = {
      discardResponseBodies: true,
      scenarios: {
        incremental_load: {
          executor: 'ramping-vus',
          startVUs: 0,
          stages: Array.from({ length: MAX_VU / STEP_SIZE }, (_, i) => ({
            duration: STEP_DURATION,
            target: (i + 1) * STEP_SIZE,
          })),
          gracefulRampDown: '30s',
        },
      },
      thresholds: {
        error_rate: ['rate<0.1'], // éŒ¯èª¤çŽ‡ < 10%
        response_time: ['p(95)<5000'], // P95 < 5 ç§’
      },
    };

    export function handleSummary(data) {
      console.log('ðŸ“Š å£“æ¸¬å®Œæˆï¼Œè¼¸å‡ºçµæžœä¸­...');
      return {
        '/results/auto-limit.json': JSON.stringify(data, null, 2),
      };
    }

