{{- if .Values.audit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.audit.existingConfiguration }}
data:
{{ tpl (.Files.Glob "configuration/audit/*").AsConfig . | nindent 2 }}
{{- end }}