{{- if .Values.service.httpd.enabled }}
{{- $svcPort := ternary 1443 1080 .Values.httpd.tls.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpd.serviceName" . }}
  labels:
    {{- include "httpd.labels" . | nindent 4 }}
  {{- with .Values.service.httpd.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.httpd.type }}
  ports:
    - port: {{ $svcPort }}
      targetPort: {{ $svcPort }}
      protocol: "TCP"

  selector:
    {{- include "httpd.selectorLabels" . | nindent 4 }}
{{- end }}