{{- if .Values.backupJob.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redcap.secrets.backup.rclone.conf.name" . }}
type: Opaque
data: 
  rclone.conf: {{ tpl (.Files.Get "configuration/redcap/backup/rclone.conf") . | b64enc | quote }}
{{- end }}