apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redcap.secrets.database.creds.name" . }}
type: Opaque
data: 
  credentials.php: {{ tpl (.Files.Get "configuration/redcap/database-conf/creds/credentials.php") . | b64enc | quote }}
