apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redcap.secrets.msmtprc.conf.name" . }}
type: Opaque
data: 
  msmtprc: {{ tpl (.Files.Get "configuration/redcap/mail-conf/creds/msmtprc") . | b64enc | quote }}