{{- if .Values.restoreJob.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redcap.secrets.restore.rclone.conf.name" . }}
type: Opaque
data: 
  rclone.conf: {{ tpl (.Files.Get "configuration/redcap/restore/rclone.conf") . | b64enc | quote }}
{{- end }}