apiVersion: batch/v1
kind: CronJob
metadata:
  name: redcap-restore-job
  labels:
    app.kubernetes.io/name: redcap-restore-job
    app.kubernetes.io/instance: redcap
    app.kubernetes.io/role: redcap-restore-job
spec:
  schedule: "0 0 1 1 *"  
  suspend: true          
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
          containers:
          - name: redcap-restore
            image: bitnamilegacy/mysql:9.3.0-debian-12-r1
            imagePullPolicy: IfNotPresent
            command:
            - sh
            - -c
            - |
              /scripts/restore.sh /backup-data/redcap-backup-latest.tar.gz
            envFrom:
            - configMapRef:
                name: redcap-db-config
            env:
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: redcap-mysql
                  key: mysql-root-password
            volumeMounts:
            - name: redcap-code
              mountPath: /redcap
            - name: edocs
              mountPath: /edocs
            - name: backup-pvc
              mountPath: /backup-data
            - name: restore
              mountPath: /restore-data
            - name: backup-scripts
              mountPath: /scripts
          volumes:
          - name: redcap-code
            persistentVolumeClaim:
              claimName: redcap-app-pvc
          - name: edocs
            persistentVolumeClaim:
              claimName: redcap-edocs-pvc
          - name: backup-pvc
            persistentVolumeClaim:
              claimName: redcap-backup-pvc
          - name: backup-scripts
            configMap:
              name: redcap-backup-scripts
              defaultMode: 0755
          - name: restore
            emptyDir: {}
