apiVersion: v1
kind: ConfigMap
metadata:
  name: redcap-nginx
data:
  redcap.conf: |
    server {
        listen 1080;
        listen 1443 ssl;

        server_name _;

        root /var/www/redcap;

        index index.php index.html;

        access_log /dev/stdout;
        error_log /dev/stderr;

        # TLS 憑證設定（掛載 redcap-tls secret）
        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }
        location = /healthz {
            fastcgi_pass redcap-svc:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root/healthz.php;
            fastcgi_param SCRIPT_NAME /healthz.php;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass redcap-svc:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 3600;
        }

        location /static {
            alias /var/www/static;
            autoindex on;
        }
    }
