name: redcap-helmchart-ci
run-name: Helm Chart CI triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  aphp-chart-ci-workflow:
    uses: aphp/ci-workflows/.github/workflows/chart-ci.yml@dev
    with:
      chart-dir: "charts/redcap"
      chart-values: "charts/redcap/values.yaml"