name: redcap-helmchart-c
run-name: Helm Chart CI triggered by @${{ github.actor }}

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  aphp-chart-ci-workflow:
    uses: aphp/ci-workflows/.github/workflows/chart-ci.yml@dev
    with:
      chart-dir: "charts/redcap"